---
$schema: "http://json-schema.org/draft-06/schema#"
blast:
  blast:
    default: false
    description: "Boolean to indicate the use of the BLAST clustering algorithm to assign taxonomic information to the OTUs."
    type: boolean
  database:
    default: SILVA
    description: "Database against which the BLAST should be carried out, at the moment \"NCBI\" and \"SILVA\" are supported."
    oneOf: "SILVA, NCBI"
    type: string
  db_path:
    default: database/silva/silva.db
    description: "Path to the database file against which the BLAST should be carried out, at the moment only the SILVA and NCBI databases will be automatically downloaded, other databases have to be downloaded and configurated manually."
    type: string
  drop_tax_classes:
    default: ""
    description: "Comma-sparated list of taxations to dismiss. Either by name, id or regular expression"
    type: string
  evalue:
    default: 1e-51
    description: "Highest accepted evalue."
    type: string
  ident:
    default: 90.0
    description: "Minimal identity overlap between target and query sequence."
    type: float
  max_target_seqs:
    default: 1
    description: "Number of blast hits that are saved per sequence / OTU."
    type: int
chim:
  abskew:
    default: 16
    description: "Minimum abundance skew, definied by (min(abund.(paren1), abund.(paren2))) / abund.(child)."
    type: int
  beta:
    default: 8.0
    description: "Weight of a \"no\" vote for the VSEARCH chimera detection algorithm."
    type: float
  pseudo_count:
    default: 1.2
    description: "Pseudo - count prior on number of “no” votes."
    type: float
derep:
  clustering:
    default: 1.0
    description: "Percent identity for cdhit (dereplication) (1 = 100%), if cdhit is solely to be used for dereplication (recommended), keep the default value."
    maximum: 1.0
    minimum: 0.1
    type: float
  length_overlap:
    default: 0.0
    description: "Length difference cutoff, default 0.0 if set to 0.9, the shorter sequences need to be at least 90% length of the representative of the cluster."
    maximum: 1.0
    minimum: 0.0
    type: float
  representative:
    default: longest
    description: "Which sequence to use as a representative sequence per CDHIT cluster. longest = the longest sequence of the corresponding cluster, most_common = the most common sequence of the corresponding cluster."
    oneOf: "longest, most_common"
    type: string
description: "Schema for the configfile."
general:
  already_assembled:
    default: false
    description: "Skipping of the quality control and read assembly steps for data that is already assembled."
    type: boolean
  cores:
    default: 4
    description: "Amount of cores available for the workflow."
    exclusiveMinimum: 0
    type: int
  demultiplexing:
    default: false
    description: "Demultiplexing for reads that were not demultiplexed by the sequencing company (slow)."
    type: boolean
  filename:
    default: project
    description: "The filename of the project folder, primertable (.csv) and config file (.yaml)."
    type: string
  multiqc:
    default: false
    description: "Initial quality check (fastqc & multiqc), currently only works for not yet assembled reads."
    type: boolean
  primertable:
    default: project.csv
    description: "Path to the primertable."
    type: string
  read_sorting:
    default: false
    description: "Read sorting for paired end reads that were not sorted by the sequencing company (slow)."
    type: boolean
  units:
    default: units.tsv
    description: "Path to the sequencing unit sheet."
    type: string
  seq_rep:
    default: OTU
    description: "How the sequences should be represented, possible values are: 'ASV', amplicon sequence variants, created with DADA2 or 'OTU', operational taxonomic units, created with SWARM"
    oneOf: "OTU, ASV"
    type: string
merge:
  ampli_corr:
    default: fdr
    description: "Specifies the correction method for Fisher's exact test."
    oneOf: "fdr, holm, hochberg, hommel, bonferroni, BH, BY, none"
    type: string
  ampliconduo:
    default: false
    description: "If AmpliconDuo should be used for statistical analysis of the data."
    type: boolean
  cutoff:
    default: 3
    description: "An additional abundance filter if the split sample approach was not used."
    type: int
  filter_method:
    default: not_split
    description: "If the split sample approach was used (split_sample) or not (not_split)."
    oneOf: "not_split, split_sample"
    type: string
  name_ext:
    default: R1
    description: "The identifier for the forward read (for the reverse read the 1 is switched with 2, if the data is in paired-end format), has to be included at the end of the file name, before the file format identifier (including for single end files)."
    type: string
  paired_End:
    default: true
    description: "The format of the sequencing data, TRUE if the reads are in paired-end format."
    type: boolean
  plot_AmpDuo:
    default: true
    description: "If the frequency-frequency plot should be saved."
    type: boolean
  save_format:
    default: png
    description: "File format for the frequency-frequency plot."
    oneOf: "png, eps, ps, tex, pdf, jpeg, tiff, bmp, svg, wmf"
    type: string
  swarm:
    default: true
    description: "Boolean to indicate the use of the SWARM clustering algorithm to create operational taxonomic units (OTUs) from the data."
    type: boolean
qc:
  all_primer:
    default: true
    description: "Boolean that indicates if the sequence is free of any kind of additional subsequences (primer, barcodes etc.)."
    type: boolean
  barcode_removed:
    default: true
    description: "Boolean that indicates if the sequence is free of barcodes."
    type: boolean
  maxlen:
    default: 600
    description: "The maximal length of a sequence after primer removal to be accepted by PANDAseq."
    minimum: 10
    type: int
  minlen:
    default: 100
    description: "The minimal length of a sequence after primer removal to be accepted by PANDAseq."
    minimum: 10
    type: int
  minoverlap:
    default: 15
    description: "Sets the minimum overlap between forward and reverse reads."
    maximum: 50
    minimum: 1
    type: int
  minqual:
    default: 1
    description: "Minimal quality score for bases in an assembled read to be accepted by PANDAseq."
    minimum: 1
    type: int
  mq:
    default: 25
    description: "Minimum quality sequence check (prinseq), filtering of sequences according to the PHRED quality score before the assembly."
    minimum: 0
    type: int
  primer_offset:
    default: false
    description: "Using PANDAseq to remove primer sequences by length offset instead of sequence identity."
    type: boolean
  threshold:
    default: 0.9
    description: "PANDAseq score threshold a sequence must meet to be kept in the output."
    maximum: 1.0
    minimum: 0.0
    type: float
